apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: jms-example.client
spec:
  username: test
  authentication:
    type: password
    password: dGVzdA==
  authorization:
    - operations: ["send", "recv"]
      addresses: ["*"]
